version: '3'
services:
  task-container-app: 
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_NAME: task_db
      DB_USER: postgres
      DB_PASSWORD: elcasero212
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elcasero212